# Generated by Django 4.2.7 on 2025-08-28 12:20

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentPlan',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('fixed_amount', models.DecimalField(decimal_places=6, help_text='Fixed investment amount for this plan', max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('roi_rate', models.DecimalField(decimal_places=2, help_text='ROI rate as percentage per cycle', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='daily', max_length=10)),
                ('duration_days', models.PositiveIntegerField(help_text='Total duration of investment in days', validators=[django.core.validators.MinValueValidator(1)])),
                ('breakdown_window_days', models.PositiveIntegerField(help_text='Days from start date when breakdown is allowed', validators=[django.core.validators.MinValueValidator(1)])),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended')], default='active', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Investment Plan',
                'verbose_name_plural': 'Investment Plans',
                'db_table': 'investment_plan',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'is_active'], name='investment__status_3e8f33_idx'), models.Index(fields=['frequency', 'status'], name='investment__frequen_847122_idx')],
            },
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=6, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('currency', models.CharField(choices=[('INR', 'INR'), ('USDT', 'USDT')], max_length=10)),
                ('payment_method', models.CharField(choices=[('direct_payment', 'Direct Payment'), ('admin_request', 'Admin Request')], default='direct_payment', help_text='Method used to pay for this investment', max_length=20)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('roi_accrued', models.DecimalField(decimal_places=6, default=Decimal('0.000000'), max_digits=20)),
                ('last_roi_credit', models.DateTimeField(blank=True, null=True)),
                ('next_roi_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('breakdown_pending', 'Breakdown Pending'), ('breakdown_approved', 'Breakdown Approved'), ('breakdown_rejected', 'Breakdown Rejected'), ('cancelled', 'Cancelled'), ('pending_admin_approval', 'Pending Admin Approval')], default='active', max_length=25)),
                ('is_active', models.BooleanField(default=True)),
                ('approved_at', models.DateTimeField(blank=True, help_text='When this investment was approved by admin', null=True)),
                ('approved_by', models.ForeignKey(blank=True, help_text='Admin user who approved this investment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_investments', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to='investment.investmentplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Investment',
                'verbose_name_plural': 'Investments',
                'db_table': 'investment',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BreakdownRequest',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('requested_amount', models.DecimalField(decimal_places=6, help_text='Amount requested for breakdown', max_digits=20)),
                ('final_amount', models.DecimalField(decimal_places=6, help_text='Final amount after deductions', max_digits=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('investment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='breakdown_request', to='investment.investment')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_breakdowns', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breakdown_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Breakdown Request',
                'verbose_name_plural': 'Breakdown Requests',
                'db_table': 'breakdown_request',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='investment',
            index=models.Index(fields=['user', 'status'], name='investment_user_id_d45b23_idx'),
        ),
        migrations.AddIndex(
            model_name='investment',
            index=models.Index(fields=['plan', 'status'], name='investment_plan_id_255b5c_idx'),
        ),
        migrations.AddIndex(
            model_name='investment',
            index=models.Index(fields=['start_date', 'end_date'], name='investment_start_d_bef86b_idx'),
        ),
        migrations.AddIndex(
            model_name='investment',
            index=models.Index(fields=['next_roi_date'], name='investment_next_ro_5430a8_idx'),
        ),
        migrations.AddIndex(
            model_name='breakdownrequest',
            index=models.Index(fields=['user', 'status'], name='breakdown_r_user_id_804e30_idx'),
        ),
        migrations.AddIndex(
            model_name='breakdownrequest',
            index=models.Index(fields=['status', 'created_at'], name='breakdown_r_status_7c53ea_idx'),
        ),
    ]
