# Generated by Django 4.2.7 on 2025-10-15 11:04

import autoslug.fields
import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, default=None, max_length=255, null=True, unique=True, verbose_name='Category Name')),
                ('slug', autoslug.fields.AutoSlugField(blank=True, default=None, editable=False, null=True, populate_from='category', unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=8, verbose_name='Status')),
                ('order', models.IntegerField(blank=True, default=None, null=True, unique=True, verbose_name='Order')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_category', models.CharField(blank=True, default=None, max_length=255, null=True, unique=True)),
                ('slug', autoslug.fields.AutoSlugField(blank=True, default=None, editable=False, null=True, populate_from='sub_category', unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=8, verbose_name='Status')),
                ('order', models.IntegerField(blank=True, default=None, null=True, unique=True, verbose_name='Order')),
                ('category', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='blogs.category', verbose_name='Select Category')),
            ],
            options={
                'verbose_name_plural': 'Subcategories',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', autoslug.fields.AutoSlugField(blank=True, default=None, editable=False, max_length=200, null=True, populate_from='blog_title', unique=True)),
                ('blog_title', models.CharField(blank=True, default=None, max_length=150, null=True, verbose_name='blog Headline')),
                ('blog_short_des', models.CharField(blank=True, default=None, max_length=160, null=True, verbose_name='Short Description')),
                ('blog_des', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='No blog', null=True, verbose_name='Long Description')),
                ('blog_image', models.ImageField(blank=True, default=None, null=True, upload_to='media/%Y/%m/%d', verbose_name='Blog Image (1280x720px)')),
                ('viewcounter', models.IntegerField(default=0, verbose_name='Views')),
                ('counter', models.IntegerField(default=100, verbose_name='Added Views')),
                ('blog_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.IntegerField(default=5, verbose_name='Order')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=8)),
                ('author', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('blog_category', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='blogs.subcategory', verbose_name='Select Category')),
            ],
            options={
                'ordering': ['-blog_date'],
            },
        ),
    ]
