# Generated by Django 4.2.7 on 2025-08-16 21:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_bankdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='USDTDetails',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('wallet_address', models.CharField(help_text='USDT wallet address for withdrawals', max_length=255)),
                ('network', models.CharField(choices=[('erc20', 'ERC20 (Ethereum)'), ('bep20', 'BEP20 (Binance Smart Chain)'), ('trc20', 'TRC20 (Tron)'), ('polygon', 'Polygon'), ('arbitrum', 'Arbitrum'), ('optimism', 'Optimism')], default='trc20', max_length=20)),
                ('wallet_name', models.CharField(blank=True, help_text='Optional name for this wallet', max_length=100, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usdt_details', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'USDT Details',
                'verbose_name_plural': 'USDT Details',
                'db_table': 'usdt_details',
            },
        ),
    ]
