# Generated by Django 4.2.7 on 2025-08-16 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_usdtdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usdtdetails',
            name='wallet_name',
        ),
        migrations.AddField(
            model_name='usdtdetails',
            name='qr_code',
            field=models.ImageField(blank=True, help_text='QR code image for the wallet address', null=True, upload_to='usdt_qr_codes/'),
        ),
    ]
