# Generated by Django 4.2.7 on 2025-08-12 09:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('target_group', models.CharField(choices=[('ALL', 'All Users'), ('VERIFIED_ONLY', 'Verified Users Only'), ('UNVERIFIED_ONLY', 'Unverified Users Only'), ('ACTIVE_INVESTORS', 'Active Investors Only'), ('ADMIN_ONLY', 'Admin Users Only')], default='ALL', max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('SCHEDULED', 'Scheduled'), ('EXPIRED', 'Expired')], default='ACTIVE', max_length=20)),
                ('priority', models.PositiveIntegerField(default=1, help_text='Higher number = higher priority (1-10)')),
                ('display_from', models.DateTimeField(default=django.utils.timezone.now, help_text='When to start displaying this announcement')),
                ('display_until', models.DateTimeField(blank=True, help_text='When to stop displaying this announcement (leave blank for permanent)', null=True)),
                ('is_pinned', models.BooleanField(default=False, help_text='Pinned announcements appear at the top')),
                ('view_count', models.PositiveIntegerField(default=0, help_text='Number of times this announcement has been viewed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Announcement',
                'verbose_name_plural': 'Announcements',
                'db_table': 'announcement',
                'ordering': ['-priority', '-is_pinned', '-created_at'],
                'indexes': [models.Index(fields=['status', 'target_group'], name='announcemen_status_7fd717_idx'), models.Index(fields=['display_from', 'display_until'], name='announcemen_display_e279ed_idx'), models.Index(fields=['is_pinned', 'priority'], name='announcemen_is_pinn_ae207c_idx')],
            },
        ),
        migrations.CreateModel(
            name='AdminActionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('USER_MANAGEMENT', 'User Management'), ('KYC_APPROVAL', 'KYC Approval'), ('WALLET_ADJUSTMENT', 'Wallet Adjustment'), ('INVESTMENT_MANAGEMENT', 'Investment Management'), ('WITHDRAWAL_APPROVAL', 'Withdrawal Approval'), ('REFERRAL_MANAGEMENT', 'Referral Management'), ('ANNOUNCEMENT', 'Announcement Management'), ('SYSTEM_CONFIG', 'System Configuration')], max_length=30)),
                ('action_description', models.TextField()),
                ('target_model', models.CharField(blank=True, max_length=100, null=True)),
                ('target_id', models.CharField(blank=True, max_length=100, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_actions', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_actions_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admin Action Log',
                'verbose_name_plural': 'Admin Action Logs',
                'db_table': 'admin_action_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['admin_user', 'action_type'], name='admin_actio_admin_u_bb8733_idx'), models.Index(fields=['action_type', 'created_at'], name='admin_actio_action__a1eff9_idx'), models.Index(fields=['target_user', 'created_at'], name='admin_actio_target__b60369_idx')],
            },
        ),
    ]
