# Generated by Django 4.2.7 on 2025-08-09 08:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kyc', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='videokyc',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_kycs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='videokyc',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_videos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='offlinekycrequest',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_kyc_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='offlinekycrequest',
            name='documents',
            field=models.ManyToManyField(blank=True, to='kyc.kycdocument'),
        ),
        migrations.AddField(
            model_name='offlinekycrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offline_kyc_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='kycverificationlog',
            name='performed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_kyc_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='kycverificationlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='kycdocument',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='kycdocument',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='kycdocument',
            unique_together={('user', 'document_type')},
        ),
    ]
