# Generated by Django 4.2.7 on 2025-08-09 08:00

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('currency', models.CharField(choices=[('INR', 'Indian Rupee'), ('USDT', 'Tether USD')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=6, max_digits=20, validators=[django.core.validators.MinValueValidator(1e-06)])),
                ('fee', models.DecimalField(decimal_places=6, default=0.0, max_digits=20, validators=[django.core.validators.MinValueValidator(0)])),
                ('payout_method', models.CharField(choices=[('bank_transfer', 'Bank Transfer'), ('upi', 'UPI'), ('paytm', 'Paytm'), ('phonepe', 'PhonePe'), ('googlepay', 'Google Pay'), ('usdt_erc20', 'USDT ERC20'), ('usdt_bep20', 'USDT BEP20'), ('usdt_trc20', 'USDT TRC20')], max_length=20)),
                ('payout_details', models.TextField(help_text='JSON formatted payout details')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('tx_hash', models.CharField(blank=True, help_text='Blockchain transaction hash', max_length=255, null=True)),
                ('chain_type', models.CharField(blank=True, help_text='Chain type for USDT withdrawals', max_length=10, null=True)),
                ('gas_fee', models.DecimalField(decimal_places=6, default=0.0, max_digits=20, validators=[django.core.validators.MinValueValidator(0)])),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_withdrawals', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Withdrawal',
                'verbose_name_plural': 'Withdrawals',
                'db_table': 'withdrawals',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='withdrawals_user_id_38a9fa_idx'), models.Index(fields=['currency', 'status'], name='withdrawals_currenc_ade83c_idx'), models.Index(fields=['status', 'created_at'], name='withdrawals_status_7d3043_idx'), models.Index(fields=['payout_method', 'created_at'], name='withdrawals_payout__8814b8_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='withdrawal',
            constraint=models.CheckConstraint(check=models.Q(('amount__gt', 0)), name='positive_amount'),
        ),
        migrations.AddConstraint(
            model_name='withdrawal',
            constraint=models.CheckConstraint(check=models.Q(('fee__gte', 0)), name='non_negative_fee'),
        ),
    ]
