# Generated by Django 4.2.7 on 2025-08-28 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('withdrawals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawal',
            name='payout_method',
            field=models.CharField(choices=[('bank_transfer', 'Bank Transfer'), ('usdt_erc20', 'USDT ERC20'), ('usdt_bep20', 'USDT BEP20'), ('usdt_trc20', 'USDT TRC20')], max_length=20),
        ),
    ]
