# Generated by Django 4.2.7 on 2025-10-12 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('withdrawals', '0002_alter_withdrawal_payout_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='WithdrawalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_approve_usdt_limit', models.DecimalField(decimal_places=6, default=100, help_text='Maximum USDT amount that will be auto-approved', max_digits=20)),
                ('auto_approve_inr_limit', models.DecimalField(decimal_places=2, default=0, help_text='Maximum INR amount that will be auto-approved (0 = disabled)', max_digits=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Withdrawal Settings',
            },
        ),
    ]
