# Generated by Django 4.2.7 on 2025-10-12 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('withdrawals', '0003_withdrawalsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawal',
            name='payout_method',
            field=models.CharField(choices=[('bank_transfer', 'Bank Transfer'), ('upi_transfer', 'upi Transfer'), ('usdt_erc20', 'USDT ERC20'), ('usdt_bep20', 'USDT BEP20'), ('usdt_trc20', 'USDT TRC20')], max_length=20),
        ),
    ]
