# Generated by Django 4.2.7 on 2025-08-12 07:27

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('DEPOSIT', 'Deposit'), ('WITHDRAWAL', 'Withdrawal'), ('ROI', 'ROI Payout'), ('REFERRAL_BONUS', 'Referral Bonus'), ('MILESTONE_BONUS', 'Milestone Bonus'), ('ADMIN_ADJUSTMENT', 'Admin Adjustment'), ('PLAN_PURCHASE', 'Investment Plan Purchase'), ('BREAKDOWN_REFUND', 'Investment Breakdown Refund')], help_text='Type of transaction', max_length=20)),
                ('currency', models.CharField(choices=[('INR', 'Indian Rupee'), ('USDT', 'Tether')], help_text='Currency of the transaction', max_length=10)),
                ('amount', models.DecimalField(decimal_places=6, help_text='Transaction amount', max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.000001'))])),
                ('reference_id', models.CharField(blank=True, help_text='Reference ID to related object (e.g., investment ID, withdrawal ID)', max_length=255, null=True)),
                ('meta_data', models.JSONField(blank=True, default=dict, help_text='Additional transaction metadata (tx hash, bank details, notes, etc.)')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='SUCCESS', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'db_table': 'transaction',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'type'], name='transaction_user_id_81f5d7_idx'), models.Index(fields=['user', 'currency'], name='transaction_user_id_a22876_idx'), models.Index(fields=['user', 'status'], name='transaction_user_id_442e5b_idx'), models.Index(fields=['type', 'created_at'], name='transaction_type_e60e19_idx'), models.Index(fields=['currency', 'created_at'], name='transaction_currenc_6c5768_idx'), models.Index(fields=['status', 'created_at'], name='transaction_status_cb5aa3_idx'), models.Index(fields=['reference_id'], name='transaction_referen_fd9611_idx'), models.Index(fields=['created_at'], name='transaction_created_789427_idx')],
            },
        ),
    ]
