# Generated by Django 4.2.7 on 2025-08-12 07:33

import app.transactions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_alter_transaction_meta_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='meta_data',
            field=models.JSONField(blank=True, default=app.transactions.models.get_meta_data_default, help_text='Additional transaction metadata (tx hash, bank details, notes, etc.)'),
        ),
    ]
